django/savecmpo/main/urls.py
from django.urls import path
from .views import Home, thank, load_index

urlpatterns = [
    path('', Home , name='home'),
    path('thank/',thank, name='thank'),
    path('ajax/load-index/', load_index, name='ajax-load-index'),

]

django/savecmpo/savecmpo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main.views import Home, thank, load_index
from backend.views import Index, SavecmpoListView, SavecmpoDetailview, Search, Searchlist, exportexcel

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', Home, name='home'),
    path('thank/', thank, name='thank'),
    path('ajax/load-index/', load_index, name='ajax-load-index'),
    path('index/', Index, name='index'),
    path('listview/', SavecmpoListView.as_view(), name='listview'),
    path('detailview/<int:pk>', SavecmpoDetailview.as_view(), name='detailview'),
    path('search/', Search, name='search'),
    path('searchlist/', Searchlist, name='searchlist'),
    path('exportexcel/', exportexcel, name='exportexcel'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/savecmpo/main/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.db.models.fields.related import ForeignKey
from PIL import Image
from django.urls import reverse

# Create your models here.

class Duty(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Cchangwat(models.Model):
    changwatcode = models.CharField(max_length=2)
    changwatname = models.CharField(max_length=155)
    zonecode = models.CharField(max_length=2)
    changwatname_en = models.CharField(max_length=155)

    def __str__(self):
        return self.changwatname

class Campur(models.Model):
    ampurcode = models.CharField(max_length=2)
    ampurname = models.CharField(max_length=155)
    ampurcodefull = models.IntegerField()
    changwatcode = models.ForeignKey(Cchangwat, on_delete=models.CASCADE)

    def __str__(self):
        return self.ampurname

class Ctambon(models.Model):
    tamboncode = models.CharField(max_length=2)
    tambonname = models.CharField(max_length=155)
    tamboncodefull = models.CharField(max_length=6)
    ampurcode = models.ForeignKey(Campur, on_delete=models.CASCADE)
    changwatcode = models.ForeignKey(Cchangwat, on_delete=models.CASCADE)

    def __str__(self):
        return self.tambonname

class Savecmpo(models.Model):
    sex = (
        ('1','ชาย'),
        ('2','หญิง'),
    )

    fname = models.CharField(max_length=255)
    lname = models.CharField(max_length=255)
    gender = models.CharField(max_length=10, choices=sex, default='ชาย')
    age = models.IntegerField()
    id_card = models.CharField(max_length=15)
    mobile_phone = models.CharField(max_length=10)
    mobile_partner = models.CharField(max_length=10, null=True, blank=True)
    date_arrive = models.DateField(default=datetime.date.today)
    date_leave = models.DateField(default=datetime.date.today)
    Cchangwat = models.ForeignKey(Cchangwat, on_delete=models.CASCADE)
    campur = models.ForeignKey(Campur, on_delete=models.CASCADE)
    ctambon = models.ForeignKey(Ctambon, on_delete=models.CASCADE)
    moo = models.CharField(max_length=255, null=True, blank=True)
    house = models.CharField(max_length=255)
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE)
    vaccine_pic = models.ImageField(default='default.jpg', upload_to ='vaccine_pic/')
    sickness = models.ImageField(default='default.jpg', upload_to ='sickness/')
    lab = models.ImageField(default='default.jpg', upload_to='lab/')
    input_date = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(Savecmpo, self).save(*args, **kwargs)

    def __str__(self):
        return self.fname+' - '+self.lname+' - '+self.id_card

    def get_absolute_url(self):
        return reverse("detailview", kwargs={"pk": self.pk})
    

django/savecmpo/main/forms.py
from django import forms
from main.models import Ctambon, Savecmpo

class InputForm(forms.ModelForm):

    class Meta:
        model = Savecmpo

        fields = (
            'fname','lname','gender','age','id_card','mobile_phone','mobile_partner','date_arrive','date_leave','Cchangwat'
            ,'campur','ctambon','moo','house','duty','vaccine_pic','sickness','lab'
        )

        labels = {
            'fname':'ชื่อ'
            ,'lname':'นามสกุล'
            ,'gender':'เพศ'
            ,'age':'อายุ'
            ,'id_card':'เลขประชาชน/พาสปอร์ต/ประกันสังคม'
            ,'mobile_phone':'เบอร์โทรศัพท์มือถือ'
            ,'mobile_partner':'เบอร์โทรศัพท์มือถือคนใกล้ชิด'
            ,'date_arrive':'วันที่มาถึงชุมพร'
            ,'date_leave':'วันที่ออกจากชุมพร'
            ,'Cchangwat':'มาจากจังหวัด'
            ,'campur':'อำเภอที่พักในชุมพร'
            ,'ctambon':'ตำบลที่พักในชุมพร'
            ,'moo':'หมู่บ้าน ถนน อาคาร ตึก ร้านค้า โรงแรม ที่พัก ถนน'
            ,'house':'บ้านเลขที่ ห้องพักเลขที่'
            ,'duty':'เหตุผลในการเดินทางมาชุมพร'
            ,'vaccine_pic':'ใบรับรองการฉีดวัคซีน'
            ,'sickness':'ใบรับรองแพทย์ป่วยโควิด-19 ไม่เกิน 90 วัน'
            ,'lab':'ใบรับรองผลการตรวจหาเชื้อโควิด-19'
        }

        widgets = {
            'fname': forms.TextInput(attrs={'placeholder':'ชื่อตามบัตรประชาชน'})
            ,'lname':forms.TextInput(attrs={'placeholder':'นามสกุล'})
            ,'gender':forms.Select(attrs={'placeholder':'เพศ'})
            ,'age':forms.TextInput(attrs={'placeholder':'อายุ'})
            ,'id_card':forms.TextInput(attrs={'placeholder':'เลขประจำตัวประชาชน'})
            ,'mobile_phone':forms.TextInput(attrs={'placeholder':'เบอร์โทรศัพท์มือถือ'})
            ,'mobile_partner':forms.TextInput(attrs={'placeholder':'เบอร์โทรศัพท์มือถือคนใกล้ชิด'})
            ,'date_arrive':forms.SelectDateWidget(attrs={'placeholder':'วันที่เดินทางมาถึงชุมพร'})
            ,'date_leave':forms.SelectDateWidget(attrs={'placeholder':'วันที่เดินทางออกจากชุมพร'})
            ,'moo':forms.TextInput(attrs={'placeholder':'หมู่บ้าน ถนน อาคาร ตึก ร้านค้า โรงแรม ที่พัก ถนน'})
            ,'house':forms.TextInput(attrs={'placeholder':'บ้านเลขที่ ห้องพักเลขที่'})
            ,'duty':forms.Select(attrs={'placeholder':'เหตุผลในการเดินทาง'})

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ctambon'].queryset=Ctambon.objects.none()

        if 'campur' in self.data:
            try:
                ampurcodefull = int(self.data.get('campur'))
                self.fields['ctambon'].queryset=Ctambon.objects.filter(ampurcode_id=ampurcodefull).order_by('tambonname')
            except(ValueError,TypeError):
                pass            

        elif self.instance.pk:
            self.fields['ctambon'].queryset = self.instance.campur.ctambon_set.order_by('tambonname')

django/savecmpo/main/views.py
from django import forms
from django.shortcuts import render, redirect
from main.forms import InputForm
from .models import Ctambon


# Create your views here.
def Home(request):

    if request.method =='POST':
        form = InputForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('thank')
    else:
        form = InputForm()
    return render(request, 'main/home.html', {'form':form})

def thank(request):

    return render(request, 'main/thank.html')

def load_index(request):

    ampurcodefull = request.GET.get('campur')
    indexes = Ctambon.objects.filter(ampurcode_id=ampurcodefull).order_by('tambonname')
    return render(request, 'main/index_dropdown_list_option.html',{'indexes':indexes})

django/savecmpo/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
    <title>Save Chumphon</title>

</head>
<body>
    <header id="header">
        <a class="logo" href="{% url 'home' %}" >Save Chumphon</a>
    </header>
        <div class="inner">
            <div class="content">
                <div class="row">
                <!-- Form -->
                <h3></h3>

                    {% block content %}

                    {% endblock content %}

            </div>
            <div class="col=12">
                <h4><a href="http://www.cmpo.moph.go.th/cmpo/">&copy; สำนักงานสาธารณสุขจังหวัดชุมพร</a>&nbsp;&nbsp;&nbsp;<a href="https://www.facebook.com/ชุมพรจัดทัพรับมือโควิด-100999761553351"><i class="icon fa-facebook">&nbsp;</i>Facebook ชุมพรจัดทัพรับมือโควิด</a></h4>
            </div>
        </div>

<!-- Scripts -->
	<script src="{% static 'assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'assets/js/browser.min.js' %}"></script>
	<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
	<script src="{% static 'assets/js/util.js' %}"></script>
	<script src="{% static 'assets/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

django/savecmpo/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data" id="inputForm" data-index-url="{% url 'ajax-load-index' %}" novalidate>
    {% csrf_token %}
    <table>
        <!--form.as_table-->
    </table>

    <div class="row gtr-uniform">
        <div class="col-12">
            {{form.fname|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.lname|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.gender|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.age|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.id_card|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.mobile_phone|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.mobile_partner|as_crispy_field}}
        </div>
        <div class="col-12">
            <label for="">วันที่เดินทางมาถึงจังหวัดชุมพร</label>
            {{form.date_arrive}}
        </div>
        <div class="col-12">
            <label for="">วันที่เดินทางออกจากจังหวัดชุมพร</label>
            {{form.date_leave}}
        </div>
        <div class="col-12">
            {{form.Cchangwat|as_crispy_field}}
        </div>
        <div class="col-12">
             {{form.campur|as_crispy_field}}
             <label for="">หลังจากเลือกอำเภอเสร็จแล้ว รอ 1 วินาทีเพื่อกดเลือกตำบล</label>
        </div>
        <!-- Break -->
        <div class="col-12">
            {{form.ctambon|as_crispy_field}}
            <label for="">หากยังไม่ปรากฏชื่อตำบลให้กดเลือกตำบลที่พักอีก 1 ครั้ง</label>
        </div>
        <div class="col-12">
            {{form.moo|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.house|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.duty|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.vaccine_pic|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.sickness|as_crispy_field}}
        </div>
        <div class="col-12">
            {{form.lab|as_crispy_field}}
        </div>

        <div class="col-12">
            <ul class="actions">
                <li><input type="submit" value="ยืนยันข้อมูล" class="primary" /></li>
                <li><input type="reset" value="ยกเลิก" /></li>
            </ul>
        </div>
        <div class="col-12">
            <ul class="actions">
                <li><label for="">หากกดยืนยันข้อมูลแล้วระบบไม่ตอบรับ ให้ท่านกลับไปเลือกตำบลอีกครั้ง แล้วกดยืนยันข้อมูล</label></li>
                
            </ul>
        </div>
    </div>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_campur").change(function () {
        var url = $("#inputForm").attr("data-index-url");
        var ampurcodefull = $(this).val();

        $.ajax({
        url: url,
        data: {
            'campur': ampurcodefull
        },
        success: function (data) {
            $("#id_ctambon").html(data);
        }
        });

    });
    </script>

{% endblock content %}

django/savecmpo/main/templates/main/index_dropdown_list_option.html
<option value="">---------</option>
{% for index in indexes %}
<option value="{{ index.pk }}">&nbsp;{{index.tambonname}}</option>
{% endfor %}

django/savecmpo/main/templates/main/thank.html
{% extends 'main/base.html' %}

{% block content %}
<header id="header">
        <a class="logo" href="{% url 'home' %}" >กลับสู่หน้าหลัก</a>
</header>

    <div class="col-12">
        </br></br>
            <h2>ข้อมูลได้รับการบันทึกแล้ว</h2>
            <h2>ขอบคุณที่ให้เกียรติชาวชุมพร</h2>

    </div>

{% endblock content %}